services:

    payu.manager:
        class: %payu.manager.class%
        arguments:
            use.stg: %payu.use.stg%
            merchant.key: %payu.merchant.key%
            merchant.id: %payu.merchant.id%
            serializer: @serializer
            request.factory: @payu.factory.payurequest
            details.factory: @payu.factory.details
            payment.event.dispatcher: @payment.event.dispatcher
            payment.bridge: @payment.bridge

    payu.routes.loader:
        class: %payu.routes.loader.class%
        arguments:
            payu.controller.route.notify.name: %payu.controller.route.notify.name%
            payu.controller.route.notify.schemes: %payu.controller.route.notify.schemes%
            payu.controller.route.notify: %payu.controller.route.notify%
        tags:
            - { name: routing.loader }

    payu.visanet.routes.loader:
        class: %payu.visanet.routes.loader.class%
        arguments:
            payu.visanet.controller.route.execute.name: %payu.visanet.controller.route.execute.name%
            payu.visanet.controller.route.execute.schemes: %payu.visanet.controller.route.execute.schemes%
            payu.visanet.controller.route.execute: %payu.visanet.controller.route.execute%
        tags:
            - { name: routing.loader }

    #
    # Factories
    #
    payu.factory.payurequest:
        class: %payu.factory.payurequest.class%
        arguments:
            payu.language: %payu.language%
            payu.test: %payu.test%
            payu.merchant.factory: @payu.factory.merchant

    payu.factory.payutransaction:
        class: %payu.factory.payutransaction.class%

    payu.factory.merchant:
        class: %payu.factory.merchant.class%
        arguments:
            payu.merchant.login: %payu.merchant.login%
            payu.merchant.key: %payu.merchant.key%

    payu.factory.order:
        class: %payu.factory.order.class%
        arguments:
            payu.account.id: %payu.merchant.account_id%
            payu.language: %payu.language%

    payu.factory.user:
        class: %payu.factory.user.class%

    payu.factory.additionalvalue:
        class: %payu.factory.additionalvalue.class%

    payu.factory.details:
        class: %payu.factory.details.class%
