services:

    paymill.form.type:
        class: %paymill.form.type.class%
        arguments:
            router: @router
            payment.bridge: @payment.bridge
            paymill.controller.route.name: %paymill.controller.route.name%
            paymill.form.submit.label: %paymill.form.submit.label%
            paymill.form.submit.css_class: %paymill.form.submit.css.class%
        tags:
            - { name: form.type, alias: paymill_view }

    paymill.transaction.wrapper:
        class: %paymill.transaction.wrapper.class%
        arguments:
            paymill.private.key: %paymill.private.key%

    paymill.manager:
        class: %paymill.manager.class%
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            payment.transaction.wrapper: @paymill.transaction.wrapper
            payment.bridge: @payment.bridge

    paymill.twig.extension:
        class: %paymill.twig.extension.class%
        arguments:
            paymill.public.key: %paymill.public.key%
            form.factory: @form.factory
            payment.bridge: @payment.bridge
            view_template: %paymill.templates.view_template%
            scripts_template: %paymill.templates.scripts_template%
        tags:
            - { name: twig.extension }

    paymill.routes.loader:
        class: %paymill.routes.loader.class%
        arguments:
            paymill.controller.route.name: %paymill.controller.route.name%
            paymill.controller.route: %paymill.controller.route%
        tags:
            - { name: routing.loader }
